import Head from 'next/head'
import { NextPage } from 'next'
import NextLink from 'next/link'
import {
  Card,
  CardContent,
  Grid,
  Typography,
  Link,
  CardActionArea
} from '@mui/material'

import { monthNames } from '@/utils/months'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{ padding: 25 }}>
        <Grid container spacing={2}>
          {monthNames.map((month, index) => (
            <Grid key={index} item>
              <NextLink legacyBehavior href={`/months/${month}`}>
                <Link>
                  <Card
                    sx={{
                      width: 275,
                      backgroundColor: '#9DA2AE'
                    }}
                  >
                    <CardActionArea
                      sx={{
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center'
                      }}
                    >
                      <CardContent>
                        <Typography
                          sx={{ fontSize: 25, textDecoration: 'none' }}
                          color='black'
                        >
                          {month}
                        </Typography>
                      </CardContent>
                    </CardActionArea>
                  </Card>
                </Link>
              </NextLink>
            </Grid>
          ))}
        </Grid>
      </main>
    </>
  )
}

export default Home
